/* Generated by Yosys 0.48+51 (git sha1 17a53b838, g++ 12.2.0-14 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:1.1-11.10" *)
module MCE(A, B, MAX, MIN);
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:2.39-2.40" *)
  input [7:0] A;
  wire [7:0] A;
  (* force_downto = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:15.21-15.22" *)
  wire [7:0] A_MISTRAL_IB_PAD_O;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:3.39-3.40" *)
  input [7:0] B;
  wire [7:0] B;
  (* force_downto = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:17.21-17.22" *)
  wire [7:0] B_MISTRAL_IB_PAD_O;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:4.39-4.42" *)
  output [7:0] MAX;
  wire [7:0] MAX;
  wire [7:0] MAX_MISTRAL_OB_PAD_I;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:5.39-5.42" *)
  output [7:0] MIN;
  wire [7:0] MIN;
  wire [7:0] MIN_MISTRAL_OB_PAD_I;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [4:0] MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:43.11-47.10|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  (* unused_bits = "0" *)
  wire MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CO;
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD (
    .O(A_MISTRAL_IB_PAD_O[7]),
    .PAD(A[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD_1 (
    .O(A_MISTRAL_IB_PAD_O[6]),
    .PAD(A[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD_2 (
    .O(A_MISTRAL_IB_PAD_O[5]),
    .PAD(A[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD_3 (
    .O(A_MISTRAL_IB_PAD_O[4]),
    .PAD(A[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD_4 (
    .O(A_MISTRAL_IB_PAD_O[3]),
    .PAD(A[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD_5 (
    .O(A_MISTRAL_IB_PAD_O[2]),
    .PAD(A[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD_6 (
    .O(A_MISTRAL_IB_PAD_O[1]),
    .PAD(A[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB A_MISTRAL_IB_PAD_7 (
    .O(A_MISTRAL_IB_PAD_O[0]),
    .PAD(A[0])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD (
    .O(B_MISTRAL_IB_PAD_O[7]),
    .PAD(B[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD_1 (
    .O(B_MISTRAL_IB_PAD_O[6]),
    .PAD(B[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD_2 (
    .O(B_MISTRAL_IB_PAD_O[5]),
    .PAD(B[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD_3 (
    .O(B_MISTRAL_IB_PAD_O[4]),
    .PAD(B[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD_4 (
    .O(B_MISTRAL_IB_PAD_O[3]),
    .PAD(B[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD_5 (
    .O(B_MISTRAL_IB_PAD_O[2]),
    .PAD(B[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD_6 (
    .O(B_MISTRAL_IB_PAD_O[1]),
    .PAD(B[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB B_MISTRAL_IB_PAD_7 (
    .O(B_MISTRAL_IB_PAD_O[0]),
    .PAD(B[0])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD (
    .I(MAX_MISTRAL_OB_PAD_I[7]),
    .PAD(MAX[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD_1 (
    .I(MAX_MISTRAL_OB_PAD_I[6]),
    .PAD(MAX[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD_2 (
    .I(MAX_MISTRAL_OB_PAD_I[5]),
    .PAD(MAX[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD_3 (
    .I(MAX_MISTRAL_OB_PAD_I[4]),
    .PAD(MAX[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD_4 (
    .I(MAX_MISTRAL_OB_PAD_I[3]),
    .PAD(MAX[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD_5 (
    .I(MAX_MISTRAL_OB_PAD_I[2]),
    .PAD(MAX[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD_6 (
    .I(MAX_MISTRAL_OB_PAD_I[1]),
    .PAD(MAX[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MAX_MISTRAL_OB_PAD_7 (
    .I(MAX_MISTRAL_OB_PAD_I[0]),
    .PAD(MAX[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'he)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT2_Q (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .Q(MAX_MISTRAL_OB_PAD_I[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'hfbd0)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT4_Q (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[6]),
    .D(A_MISTRAL_IB_PAD_O[6]),
    .Q(MAX_MISTRAL_OB_PAD_I[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4073782080)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[0]),
    .D(A_MISTRAL_IB_PAD_O[0]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MAX_MISTRAL_OB_PAD_I[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4073782080)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_1 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[5]),
    .D(A_MISTRAL_IB_PAD_O[5]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MAX_MISTRAL_OB_PAD_I[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4073782080)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_2 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[4]),
    .D(A_MISTRAL_IB_PAD_O[4]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MAX_MISTRAL_OB_PAD_I[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4073782080)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_3 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[3]),
    .D(A_MISTRAL_IB_PAD_O[3]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MAX_MISTRAL_OB_PAD_I[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4073782080)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_4 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[2]),
    .D(A_MISTRAL_IB_PAD_O[2]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MAX_MISTRAL_OB_PAD_I[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4073782080)
  ) MAX_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_5 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[1]),
    .D(A_MISTRAL_IB_PAD_O[1]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MAX_MISTRAL_OB_PAD_I[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD (
    .I(MIN_MISTRAL_OB_PAD_I[7]),
    .PAD(MIN[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD_1 (
    .I(MIN_MISTRAL_OB_PAD_I[6]),
    .PAD(MIN[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD_2 (
    .I(MIN_MISTRAL_OB_PAD_I[5]),
    .PAD(MIN[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD_3 (
    .I(MIN_MISTRAL_OB_PAD_I[4]),
    .PAD(MIN[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD_4 (
    .I(MIN_MISTRAL_OB_PAD_I[3]),
    .PAD(MIN[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD_5 (
    .I(MIN_MISTRAL_OB_PAD_I[2]),
    .PAD(MIN[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD_6 (
    .I(MIN_MISTRAL_OB_PAD_I[1]),
    .PAD(MIN[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB MIN_MISTRAL_OB_PAD_7 (
    .I(MIN_MISTRAL_OB_PAD_I[0]),
    .PAD(MIN[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h8)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT2_Q (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .Q(MIN_MISTRAL_OB_PAD_I[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'hf420)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT4_Q (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[6]),
    .D(A_MISTRAL_IB_PAD_O[6]),
    .Q(MIN_MISTRAL_OB_PAD_I[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4246795440)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[5]),
    .D(A_MISTRAL_IB_PAD_O[5]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MIN_MISTRAL_OB_PAD_I[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4246795440)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_1 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[4]),
    .D(A_MISTRAL_IB_PAD_O[4]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MIN_MISTRAL_OB_PAD_I[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4246795440)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_2 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[3]),
    .D(A_MISTRAL_IB_PAD_O[3]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MIN_MISTRAL_OB_PAD_I[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4246795440)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_3 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[2]),
    .D(A_MISTRAL_IB_PAD_O[2]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MIN_MISTRAL_OB_PAD_I[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4246795440)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_4 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[1]),
    .D(A_MISTRAL_IB_PAD_O[1]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MIN_MISTRAL_OB_PAD_I[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4246795440)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_5 (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(B_MISTRAL_IB_PAD_O[0]),
    .D(A_MISTRAL_IB_PAD_O[0]),
    .E(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4]),
    .Q(MIN_MISTRAL_OB_PAD_I[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO (
    .A(A_MISTRAL_IB_PAD_O[7]),
    .B(B_MISTRAL_IB_PAD_O[7]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CO),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A_MISTRAL_IB_PAD_O[6]),
    .B(B_MISTRAL_IB_PAD_O[6]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A_MISTRAL_IB_PAD_O[5]),
    .B(B_MISTRAL_IB_PAD_O[5]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A_MISTRAL_IB_PAD_O[4]),
    .B(B_MISTRAL_IB_PAD_O[4]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A_MISTRAL_IB_PAD_O[3]),
    .B(B_MISTRAL_IB_PAD_O[3]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A_MISTRAL_IB_PAD_O[2]),
    .B(B_MISTRAL_IB_PAD_O[2]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A_MISTRAL_IB_PAD_O[1]),
    .B(B_MISTRAL_IB_PAD_O[1]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A_MISTRAL_IB_PAD_O[0]),
    .B(B_MISTRAL_IB_PAD_O[0]),
    .C(1'h1),
    .CI(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:43.11-47.10" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'h0000)
  ) MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(1'h1),
    .B(1'h1),
    .C(1'h1),
    .CI(1'h0),
    .CO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  assign MIN_MISTRAL_OB_PAD_I_MISTRAL_ALUT5_Q_E[3:0] = { A_MISTRAL_IB_PAD_O[3], B_MISTRAL_IB_PAD_O[3], B_MISTRAL_IB_PAD_O[7], A_MISTRAL_IB_PAD_O[7] };
endmodule
