/* Generated by Yosys 0.48+51 (git sha1 17a53b838, g++ 12.2.0-14 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:1.1-33.10" *)
module MED(BYP, DSI, CLK, DI, DO);
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:9.19-9.20" *)
  wire [7:0] A;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:9.21-9.22" *)
  wire [7:0] B;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:2.28-2.31" *)
  input BYP;
  wire BYP;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [2:0] BYP_MISTRAL_IB_PAD_O;
  wire BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:4.28-4.31" *)
  input CLK;
  wire CLK;
  wire CLK_MISTRAL_IB_PAD_O;
  wire CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:5.38-5.40" *)
  input [7:0] DI;
  wire [7:0] DI;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:6.39-6.41" *)
  output [7:0] DO;
  wire [7:0] DO;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:3.28-3.31" *)
  input DSI;
  wire DSI;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] DSI_MISTRAL_IB_PAD_O;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [2:0] DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:43.11-47.10|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI;
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_SO;
  (* abc9_carry = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_sim.v:191.132-191.134" *)
  (* unused_bits = "0" *)
  wire DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CO;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:9.31-9.37" *)
  wire [7:0] O_MUX1;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [3:0] O_MUX1_MISTRAL_ALUT4_Q_B;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] O_MUX1_MISTRAL_ALUT6_Q_1_B;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] O_MUX1_MISTRAL_ALUT6_Q_2_C;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] O_MUX1_MISTRAL_ALUT6_Q_3_A;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] O_MUX1_MISTRAL_ALUT6_Q_4_A;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] O_MUX1_MISTRAL_ALUT6_Q_6_A;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] O_MUX1_MISTRAL_ALUT6_Q_C;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[0] ;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[1] ;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[2] ;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[3] ;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[4] ;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[5] ;
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[6] ;
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[7]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q_1 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[6]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q_2 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[5]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q_3 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[4]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q_4 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[3]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q_5 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[2]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q_6 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[1]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q_7 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B[0]),
    .ENA(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q),
    .Q(A[0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* keep = 32'd1 *)
  MISTRAL_IB BYP_MISTRAL_IB_PAD (
    .O(BYP_MISTRAL_IB_PAD_O[0]),
    .PAD(BYP)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:35.36-37.10" *)
  MISTRAL_ALUT3 #(
    .LUT(8'hfb)
  ) BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A (
    .A(BYP_MISTRAL_IB_PAD_O[0]),
    .B(DSI_MISTRAL_IB_PAD_O[4]),
    .C(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(BYP_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_A_Q)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [7]),
    .ENA(1'h1),
    .Q(B[7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q_1 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [6]),
    .ENA(1'h1),
    .Q(B[6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q_2 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [5]),
    .ENA(1'h1),
    .Q(B[5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q_3 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [4]),
    .ENA(1'h1),
    .Q(B[4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q_4 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [3]),
    .ENA(1'h1),
    .Q(B[3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q_5 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [2]),
    .ENA(1'h1),
    .Q(B[2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q_6 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [1]),
    .ENA(1'h1),
    .Q(B[1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q_7 (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] [0]),
    .ENA(1'h1),
    .Q(B[0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* keep = 32'd1 *)
  MISTRAL_IB CLK_MISTRAL_IB_PAD (
    .O(CLK_MISTRAL_IB_PAD_O),
    .PAD(CLK)
  );
  MISTRAL_CLKBUF CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A (
    .A(CLK_MISTRAL_IB_PAD_O),
    .Q(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q)
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD (
    .I(A[7]),
    .PAD(DO[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_1 (
    .I(A[6]),
    .PAD(DO[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_2 (
    .I(A[5]),
    .PAD(DO[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_3 (
    .I(A[4]),
    .PAD(DO[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_4 (
    .I(A[3]),
    .PAD(DO[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_5 (
    .I(A[2]),
    .PAD(DO[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_6 (
    .I(A[1]),
    .PAD(DO[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_7 (
    .I(A[0]),
    .PAD(DO[0])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DSI_MISTRAL_IB_PAD (
    .O(DSI_MISTRAL_IB_PAD_O[3]),
    .PAD(DSI)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:35.36-37.10" *)
  MISTRAL_ALUT3 #(
    .LUT(8'hd0)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q (
    .A(A[7]),
    .B(B[7]),
    .C(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C[2]),
    .Q(DSI_MISTRAL_IB_PAD_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO (
    .A(A[7]),
    .B(B[7]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CO),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A[6]),
    .B(B[6]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A[5]),
    .B(B[5]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A[4]),
    .B(B[4]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A[3]),
    .B(B[3]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A[2]),
    .B(B[2]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A[1]),
    .B(B[1]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:58.7-63.6" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'hc3c3)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(A[0]),
    .B(B[0]),
    .C(1'h1),
    .CI(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MCE.sv:8.15-8.20|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/arith_alm_map.v:43.11-47.10" *)
  MISTRAL_ALUT_ARITH #(
    .LUT0(16'haaaa),
    .LUT1(16'h0000)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO (
    .A(1'h1),
    .B(1'h1),
    .C(1'h1),
    .CI(1'h0),
    .CO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI),
    .D0(1'h1),
    .D1(1'h1),
    .SO(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h6)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO_MISTRAL_ALUT2_Q (
    .A(A[1]),
    .B(B[1]),
    .Q(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'hd00d)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO_MISTRAL_ALUT4_Q (
    .A(A[5]),
    .B(B[5]),
    .C(A[4]),
    .D(B[4]),
    .Q(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h9909000099099909)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO_MISTRAL_ALUT6_Q (
    .A(A[6]),
    .B(B[6]),
    .C(A[3]),
    .D(B[3]),
    .E(B[2]),
    .F(A[2]),
    .Q(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hbbbbbbbbb2bbbbbb)
  ) DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT6_Q (
    .A(A[7]),
    .B(B[7]),
    .C(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[2]),
    .D(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[3]),
    .E(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[4]),
    .F(DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[5]),
    .Q(DSI_MISTRAL_IB_PAD_O[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DSI_MISTRAL_IB_PAD_O_MISTRAL_IB_O (
    .O(DSI_MISTRAL_IB_PAD_O[2]),
    .PAD(DI[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'hcca0)
  ) O_MUX1_MISTRAL_ALUT4_Q (
    .A(A[7]),
    .B(O_MUX1_MISTRAL_ALUT4_Q_B[1]),
    .C(B[7]),
    .D(DSI_MISTRAL_IB_PAD_O[3]),
    .Q(O_MUX1[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB O_MUX1_MISTRAL_ALUT4_Q_B_MISTRAL_IB_O (
    .O(O_MUX1_MISTRAL_ALUT4_Q_B[1]),
    .PAD(DI[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'he4e4e4e4f5a0e4e4)
  ) O_MUX1_MISTRAL_ALUT6_Q (
    .A(DSI_MISTRAL_IB_PAD_O[3]),
    .B(A[0]),
    .C(O_MUX1_MISTRAL_ALUT6_Q_C[2]),
    .D(B[0]),
    .E(DSI_MISTRAL_IB_PAD_O[4]),
    .F(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(O_MUX1[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hccaaccaaccf0ccaa)
  ) O_MUX1_MISTRAL_ALUT6_Q_1 (
    .A(A[1]),
    .B(O_MUX1_MISTRAL_ALUT6_Q_1_B[1]),
    .C(B[1]),
    .D(DSI_MISTRAL_IB_PAD_O[3]),
    .E(DSI_MISTRAL_IB_PAD_O[4]),
    .F(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(O_MUX1[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB O_MUX1_MISTRAL_ALUT6_Q_1_B_MISTRAL_IB_O (
    .O(O_MUX1_MISTRAL_ALUT6_Q_1_B[1]),
    .PAD(DI[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hf0ccf0ccf0aaf0cc)
  ) O_MUX1_MISTRAL_ALUT6_Q_2 (
    .A(B[2]),
    .B(A[2]),
    .C(O_MUX1_MISTRAL_ALUT6_Q_2_C[2]),
    .D(DSI_MISTRAL_IB_PAD_O[3]),
    .E(DSI_MISTRAL_IB_PAD_O[4]),
    .F(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(O_MUX1[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB O_MUX1_MISTRAL_ALUT6_Q_2_C_MISTRAL_IB_O (
    .O(O_MUX1_MISTRAL_ALUT6_Q_2_C[2]),
    .PAD(DI[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'haaccaaccaaf0aacc)
  ) O_MUX1_MISTRAL_ALUT6_Q_3 (
    .A(O_MUX1_MISTRAL_ALUT6_Q_3_A[0]),
    .B(A[3]),
    .C(B[3]),
    .D(DSI_MISTRAL_IB_PAD_O[3]),
    .E(DSI_MISTRAL_IB_PAD_O[4]),
    .F(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(O_MUX1[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB O_MUX1_MISTRAL_ALUT6_Q_3_A_MISTRAL_IB_O (
    .O(O_MUX1_MISTRAL_ALUT6_Q_3_A[0]),
    .PAD(DI[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'haaccaaccaaf0aacc)
  ) O_MUX1_MISTRAL_ALUT6_Q_4 (
    .A(O_MUX1_MISTRAL_ALUT6_Q_4_A[0]),
    .B(A[4]),
    .C(B[4]),
    .D(DSI_MISTRAL_IB_PAD_O[3]),
    .E(DSI_MISTRAL_IB_PAD_O[4]),
    .F(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(O_MUX1[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB O_MUX1_MISTRAL_ALUT6_Q_4_A_MISTRAL_IB_O (
    .O(O_MUX1_MISTRAL_ALUT6_Q_4_A[0]),
    .PAD(DI[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hf0aaf0aaf0ccf0aa)
  ) O_MUX1_MISTRAL_ALUT6_Q_5 (
    .A(A[5]),
    .B(B[5]),
    .C(DSI_MISTRAL_IB_PAD_O[2]),
    .D(DSI_MISTRAL_IB_PAD_O[3]),
    .E(DSI_MISTRAL_IB_PAD_O[4]),
    .F(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(O_MUX1[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'haaccaaccaaf0aacc)
  ) O_MUX1_MISTRAL_ALUT6_Q_6 (
    .A(O_MUX1_MISTRAL_ALUT6_Q_6_A[0]),
    .B(A[6]),
    .C(B[6]),
    .D(DSI_MISTRAL_IB_PAD_O[3]),
    .E(DSI_MISTRAL_IB_PAD_O[4]),
    .F(DSI_MISTRAL_IB_PAD_O[5]),
    .Q(O_MUX1[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB O_MUX1_MISTRAL_ALUT6_Q_6_A_MISTRAL_IB_O (
    .O(O_MUX1_MISTRAL_ALUT6_Q_6_A[0]),
    .PAD(DI[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB O_MUX1_MISTRAL_ALUT6_Q_C_MISTRAL_IB_O (
    .O(O_MUX1_MISTRAL_ALUT6_Q_C[2]),
    .PAD(DI[0])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[7]),
    .ENA(1'h1),
    .Q(\regs[0] [7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q_1  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[6]),
    .ENA(1'h1),
    .Q(\regs[0] [6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q_2  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[5]),
    .ENA(1'h1),
    .Q(\regs[0] [5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q_3  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[4]),
    .ENA(1'h1),
    .Q(\regs[0] [4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q_4  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[3]),
    .ENA(1'h1),
    .Q(\regs[0] [3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q_5  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[2]),
    .ENA(1'h1),
    .Q(\regs[0] [2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q_6  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[1]),
    .ENA(1'h1),
    .Q(\regs[0] [1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q_7  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1[0]),
    .ENA(1'h1),
    .Q(\regs[0] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [7]),
    .ENA(1'h1),
    .Q(\regs[1] [7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q_1  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [6]),
    .ENA(1'h1),
    .Q(\regs[1] [6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q_2  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [5]),
    .ENA(1'h1),
    .Q(\regs[1] [5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q_3  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [4]),
    .ENA(1'h1),
    .Q(\regs[1] [4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q_4  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [3]),
    .ENA(1'h1),
    .Q(\regs[1] [3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q_5  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [2]),
    .ENA(1'h1),
    .Q(\regs[1] [2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q_6  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [1]),
    .ENA(1'h1),
    .Q(\regs[1] [1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q_7  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] [0]),
    .ENA(1'h1),
    .Q(\regs[1] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [7]),
    .ENA(1'h1),
    .Q(\regs[2] [7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q_1  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [6]),
    .ENA(1'h1),
    .Q(\regs[2] [6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q_2  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [5]),
    .ENA(1'h1),
    .Q(\regs[2] [5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q_3  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [4]),
    .ENA(1'h1),
    .Q(\regs[2] [4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q_4  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [3]),
    .ENA(1'h1),
    .Q(\regs[2] [3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q_5  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [2]),
    .ENA(1'h1),
    .Q(\regs[2] [2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q_6  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [1]),
    .ENA(1'h1),
    .Q(\regs[2] [1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q_7  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [0]),
    .ENA(1'h1),
    .Q(\regs[2] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [7]),
    .ENA(1'h1),
    .Q(\regs[3] [7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q_1  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [6]),
    .ENA(1'h1),
    .Q(\regs[3] [6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q_2  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [5]),
    .ENA(1'h1),
    .Q(\regs[3] [5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q_3  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [4]),
    .ENA(1'h1),
    .Q(\regs[3] [4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q_4  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [3]),
    .ENA(1'h1),
    .Q(\regs[3] [3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q_5  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [2]),
    .ENA(1'h1),
    .Q(\regs[3] [2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q_6  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [1]),
    .ENA(1'h1),
    .Q(\regs[3] [1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q_7  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] [0]),
    .ENA(1'h1),
    .Q(\regs[3] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [7]),
    .ENA(1'h1),
    .Q(\regs[4] [7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q_1  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [6]),
    .ENA(1'h1),
    .Q(\regs[4] [6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q_2  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [5]),
    .ENA(1'h1),
    .Q(\regs[4] [5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q_3  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [4]),
    .ENA(1'h1),
    .Q(\regs[4] [4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q_4  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [3]),
    .ENA(1'h1),
    .Q(\regs[4] [3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q_5  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [2]),
    .ENA(1'h1),
    .Q(\regs[4] [2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q_6  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [1]),
    .ENA(1'h1),
    .Q(\regs[4] [1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q_7  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [0]),
    .ENA(1'h1),
    .Q(\regs[4] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [7]),
    .ENA(1'h1),
    .Q(\regs[5] [7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q_1  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [6]),
    .ENA(1'h1),
    .Q(\regs[5] [6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q_2  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [5]),
    .ENA(1'h1),
    .Q(\regs[5] [5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q_3  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [4]),
    .ENA(1'h1),
    .Q(\regs[5] [4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q_4  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [3]),
    .ENA(1'h1),
    .Q(\regs[5] [3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q_5  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [2]),
    .ENA(1'h1),
    .Q(\regs[5] [2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q_6  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [1]),
    .ENA(1'h1),
    .Q(\regs[5] [1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q_7  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] [0]),
    .ENA(1'h1),
    .Q(\regs[5] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [7]),
    .ENA(1'h1),
    .Q(\regs[6] [7]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q_1  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [6]),
    .ENA(1'h1),
    .Q(\regs[6] [6]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q_2  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [5]),
    .ENA(1'h1),
    .Q(\regs[6] [5]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q_3  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [4]),
    .ENA(1'h1),
    .Q(\regs[6] [4]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q_4  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [3]),
    .ENA(1'h1),
    .Q(\regs[6] [3]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q_5  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [2]),
    .ENA(1'h1),
    .Q(\regs[6] [2]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q_6  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [1]),
    .ENA(1'h1),
    .Q(\regs[6] [1]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/sagouzal-23/projse04/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q_7  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [0]),
    .ENA(1'h1),
    .Q(\regs[6] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  assign { O_MUX1_MISTRAL_ALUT4_Q_B[3:2], O_MUX1_MISTRAL_ALUT4_Q_B[0] } = { DSI_MISTRAL_IB_PAD_O[3], B[7], A[7] };
  assign DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C[1:0] = { B[7], A[7] };
  assign DSI_MISTRAL_IB_PAD_O_MISTRAL_ALUT3_Q_C_MISTRAL_ALUT_ARITH_SO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_CI_MISTRAL_ALUT_ARITH_CO_SO[1:0] = { B[7], A[7] };
  assign BYP_MISTRAL_IB_PAD_O[2:1] = DSI_MISTRAL_IB_PAD_O[5:4];
  assign O_MUX1_MISTRAL_ALUT6_Q_3_A[5:1] = { DSI_MISTRAL_IB_PAD_O[5:3], B[3], A[3] };
  assign { O_MUX1_MISTRAL_ALUT6_Q_2_C[5:3], O_MUX1_MISTRAL_ALUT6_Q_2_C[1:0] } = { DSI_MISTRAL_IB_PAD_O[5:3], A[2], B[2] };
  assign { O_MUX1_MISTRAL_ALUT6_Q_1_B[5:2], O_MUX1_MISTRAL_ALUT6_Q_1_B[0] } = { DSI_MISTRAL_IB_PAD_O[5:3], B[1], A[1] };
  assign { O_MUX1_MISTRAL_ALUT6_Q_C[5:3], O_MUX1_MISTRAL_ALUT6_Q_C[1:0] } = { DSI_MISTRAL_IB_PAD_O[5:4], B[0], A[0], DSI_MISTRAL_IB_PAD_O[3] };
  assign DSI_MISTRAL_IB_PAD_O[1:0] = { B[5], A[5] };
  assign O_MUX1_MISTRAL_ALUT6_Q_6_A[5:1] = { DSI_MISTRAL_IB_PAD_O[5:3], B[6], A[6] };
  assign O_MUX1_MISTRAL_ALUT6_Q_4_A[5:1] = { DSI_MISTRAL_IB_PAD_O[5:3], B[4], A[4] };
endmodule
