/* Generated by Yosys 0.48+51 (git sha1 17a53b838, g++ 12.2.0-14 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:1.1-33.10" *)
module MED(BYP, DSI, CLK, DI, DO);
  wire A;
  wire A_MISTRAL_FF_Q_ENA;
  wire B;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:2.28-2.31" *)
  input BYP;
  wire BYP;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [2:0] BYP_MISTRAL_IB_PAD_O;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:4.28-4.31" *)
  input CLK;
  wire CLK;
  wire CLK_MISTRAL_IB_PAD_O;
  wire CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:5.38-5.40" *)
  input [7:0] DI;
  wire [7:0] DI;
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] DI_MISTRAL_IB_PAD_O;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:6.39-6.41" *)
  output [7:0] DO;
  wire [7:0] DO;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:3.28-3.31" *)
  input DSI;
  wire DSI;
  (* force_downto = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [3:0] DSI_MISTRAL_IB_PAD_O;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:11.8-11.14" *)
  wire O_MUX1;
  wire \regs[0] ;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[1] ;
  wire \regs[2] ;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[3] ;
  wire \regs[4] ;
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:8.19-8.23" *)
  wire [7:0] \regs[5] ;
  wire \regs[6] ;
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF A_MISTRAL_FF_Q (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(B),
    .ENA(A_MISTRAL_FF_Q_ENA),
    .Q(A),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:35.36-37.10" *)
  MISTRAL_ALUT3 #(
    .LUT(8'hef)
  ) A_MISTRAL_FF_Q_ENA_MISTRAL_ALUT3_Q (
    .A(B),
    .B(BYP_MISTRAL_IB_PAD_O[1]),
    .C(A),
    .Q(A_MISTRAL_FF_Q_ENA)
  );
  (* keep = 32'd1 *)
  MISTRAL_IB BYP_MISTRAL_IB_PAD (
    .O(BYP_MISTRAL_IB_PAD_O[1]),
    .PAD(BYP)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF B_MISTRAL_FF_Q (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[6] ),
    .ENA(1'h1),
    .Q(B),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* keep = 32'd1 *)
  MISTRAL_IB CLK_MISTRAL_IB_PAD (
    .O(CLK_MISTRAL_IB_PAD_O),
    .PAD(CLK)
  );
  MISTRAL_CLKBUF CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A (
    .A(CLK_MISTRAL_IB_PAD_O),
    .Q(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q)
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DI_MISTRAL_IB_PAD (
    .O(DI_MISTRAL_IB_PAD_O[7]),
    .PAD(DI[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DI_MISTRAL_IB_PAD_1 (
    .O(DI_MISTRAL_IB_PAD_O[6]),
    .PAD(DI[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DI_MISTRAL_IB_PAD_2 (
    .O(DI_MISTRAL_IB_PAD_O[5]),
    .PAD(DI[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DI_MISTRAL_IB_PAD_3 (
    .O(DI_MISTRAL_IB_PAD_O[4]),
    .PAD(DI[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DI_MISTRAL_IB_PAD_4 (
    .O(DI_MISTRAL_IB_PAD_O[3]),
    .PAD(DI[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DI_MISTRAL_IB_PAD_5 (
    .O(DI_MISTRAL_IB_PAD_O[2]),
    .PAD(DI[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DI_MISTRAL_IB_PAD_6 (
    .O(DI_MISTRAL_IB_PAD_O[1]),
    .PAD(DI[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD (
    .I(1'h0),
    .PAD(DO[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_1 (
    .I(1'h0),
    .PAD(DO[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_2 (
    .I(1'h0),
    .PAD(DO[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_3 (
    .I(1'h0),
    .PAD(DO[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_4 (
    .I(1'h0),
    .PAD(DO[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_5 (
    .I(1'h0),
    .PAD(DO[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_6 (
    .I(1'h0),
    .PAD(DO[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB DO_MISTRAL_OB_PAD_7 (
    .I(A),
    .PAD(DO[0])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DSI_MISTRAL_IB_PAD (
    .O(DSI_MISTRAL_IB_PAD_O[1]),
    .PAD(DSI)
  );
  (* keep = 32'd1 *)
  MISTRAL_IB DSI_MISTRAL_IB_PAD_O_MISTRAL_IB_O (
    .O(DSI_MISTRAL_IB_PAD_O[2]),
    .PAD(DI[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'he2c0)
  ) O_MUX1_MISTRAL_ALUT4_Q (
    .A(B),
    .B(DSI_MISTRAL_IB_PAD_O[1]),
    .C(DSI_MISTRAL_IB_PAD_O[2]),
    .D(A),
    .Q(O_MUX1)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[0]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(O_MUX1),
    .ENA(1'h1),
    .Q(\regs[0] ),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[1]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[0] ),
    .ENA(1'h1),
    .Q(\regs[1] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[2]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[1] [0]),
    .ENA(1'h1),
    .Q(\regs[2] ),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[3]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[2] ),
    .ENA(1'h1),
    .Q(\regs[3] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[4]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[3] [0]),
    .ENA(1'h1),
    .Q(\regs[4] ),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[5]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[4] ),
    .ENA(1'h1),
    .Q(\regs[5] [0]),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/cal/exterieurs/saitfora-23/2A/SE/souhail-ait-fora/median/synthese/../src/MED.sv:23.1-31.4|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/dff_map.v:12.16-12.121|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_map.v:14.28-14.135|/comelec/softs/opt/yosys/current/bin/../share/yosys/intel_alm/common/abc9_unmap.v:9.12-9.132" *)
  MISTRAL_FF \regs[6]_MISTRAL_FF_Q  (
    .ACLR(1'h1),
    .CLK(CLK_MISTRAL_IB_PAD_O_MISTRAL_CLKBUF_A_Q),
    .DATAIN(\regs[5] [0]),
    .ENA(1'h1),
    .Q(\regs[6] ),
    .SCLR(1'h0),
    .SDATA(1'h0),
    .SLOAD(1'h0)
  );
  assign DI_MISTRAL_IB_PAD_O[0] = DSI_MISTRAL_IB_PAD_O[2];
  assign { DSI_MISTRAL_IB_PAD_O[3], DSI_MISTRAL_IB_PAD_O[0] } = { A, B };
  assign { BYP_MISTRAL_IB_PAD_O[2], BYP_MISTRAL_IB_PAD_O[0] } = { A, B };
  assign \regs[1] [7:1] = 7'h00;
  assign \regs[3] [7:1] = 7'h00;
  assign \regs[5] [7:1] = 7'h00;
endmodule
